version: "3"

services:
  webserver:
    build:
      context: ./webserver
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
